# General Help
lightning --help

# Output
Lightning App Commands
  create data        ...
  delete data        ...
  delete experiment  ...
  delete sweep       ...
  download artifacts ...
  run experiment     ...
  run sweep          ...
  show artifacts     ...
  show data          ...
  show experiments   ...
  show logs          ...
  show sweeps        ...
  stop experiment    ...
  stop sweep         ...